"""Add roles

Revision ID: 3d2d91a1e0df
Revises: b8e2177f2b50
Create Date: 2023-03-04 19:32:15.265900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d2d91a1e0df'
down_revision = 'b8e2177f2b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrolesenum = postgresql.ENUM('super_admin', 'admin', 'user', name='userrolesenum')
    userrolesenum.create(op.get_bind())
    op.add_column('user', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrolesenum'),
                                    nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
