"""create book model

Revision ID: 56026c6a3234
Revises: 
Create Date: 2023-02-27 14:13:50.452844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56026c6a3234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('Author', sa.String(), nullable=False),
    sa.Column('Title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    op.drop_table('books')
    # ### end Alembic commands ###
