"""remove nullable FK

Revision ID: e93aa6a3e046
Revises: b8583fea0756
Create Date: 2023-02-27 19:27:36.833181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93aa6a3e046'
down_revision = 'b8583fea0756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'reader_pk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'reader_pk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
